# Generated by Django 3.2.23 on 2024-03-13 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20240312_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='category',
            field=models.CharField(default='best_you', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='best_me', max_length=255),
        ),
    ]
