# Generated by Django 3.2.23 on 2024-03-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_snippet',
            field=models.CharField(default='Click Title to Read', max_length=255),
        ),
    ]
